### ISSUE TITLE
NullPointerException upon opening and closing Legacy

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/WilderForge#20]
```
[02Nov.2021 23:22:07.680] [main/INFO] [com.wildermods.wilderforge.launch.Main/]: Coremod wildermyth is loaded.
[02Nov.2021 23:22:07.680] [main/INFO] [com.wildermods.wilderforge.launch.Main/]: Coremod wilderforge is loaded.
[02Nov.2021 23:23:21.441] [main/FATAL] [LegacyDesktop/]: exiting due to fatal runtime error java.lang.NullPointerException
	at com.worldwalkergames.legacy.browse.LegacyBrowserScreen.spawnHeroes(LegacyBrowserScreen.java:425)
	at com.worldwalkergames.legacy.browse.LegacyBrowserScreen.update(LegacyBrowserScreen.java:697)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:545)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:197)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:311)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:117)
	at com.wildermods.wilderforge.launch.Main.launchGame(Main.java:51)
	at com.wildermods.wilderforge.launch.Main.main(Main.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.wildermods.wilderforge.launch.services.WilderLauncherService.lambda$0(WilderLauncherService.java:65)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[02Nov.2021 23:23:21.562] [main/FATAL] [LegacyDesktop/]: error during dispose! java.lang.NullPointerException
	at com.worldwalkergames.legacy.game.mission.controls.CameraControls.dispose(CameraControls.java:705)
	at com.worldwalkergames.legacy.game.mission.controls.WorldInputManager.after(WorldInputManager.java:157)
	at com.worldwalkergames.engine.DrivableContainer.after(DrivableContainer.java:50)
	at com.worldwalkergames.legacy.ui.Screen.after(Screen.java:61)
	at com.worldwalkergames.legacy.browse.LegacyBrowserScreen.after(LegacyBrowserScreen.java:760)
	at com.worldwalkergames.engine.DrivableContainer.after(DrivableContainer.java:50)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.after(LegacyUIRoot.java:626)
	at com.worldwalkergames.legacy.ui.MainScreen.after(MainScreen.java:249)
	at com.worldwalkergames.legacy.LegacyDesktop.dispose(LegacyDesktop.java:330)
	at com.worldwalkergames.legacy.LegacyDesktop.fatalError(LegacyDesktop.java:366)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:137)
	at com.wildermods.wilderforge.launch.Main.launchGame(Main.java:51)
	at com.wildermods.wilderforge.launch.Main.main(Main.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.wildermods.wilderforge.launch.services.WilderLauncherService.lambda$0(WilderLauncherService.java:65)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by Gamebuster19901** [comment]
This bug was introduced in 2d1da579d315358b2f9b2bf1a5f43d45b4772290

**Comment by Gamebuster19901** [comment]
Caused by BiomeMixin
