### ISSUE TITLE
Update Mixin to 0.8.4

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/WilderForge#26]

**Comment by Gamebuster19901** [comment]
Might be an upstream issue.
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/spongepowered/asm/launch/MixinLaunchPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at cpw.mods.modlauncher.ServiceLoaderStreamUtils.errorHandlingServiceLoader(ServiceLoaderStreamUtils.java:65)
	at cpw.mods.modlauncher.ServiceLoaderStreamUtils.errorHandlingServiceLoader(ServiceLoaderStreamUtils.java:60)
	at cpw.mods.modlauncher.LaunchPluginHandler.<init>(LaunchPluginHandler.java:39)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:60)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by Gamebuster19901** [comment]
Upstream issue. ModLauncher requires java 16, so MixinLaunchPlugin had to be compiled with java 16. Consider creating custom bootstrapper? Or maybe create a PR for ModLauncher.

**Comment by Gamebuster19901** [comment]
![image](https://user-images.githubusercontent.com/7155747/140570324-4392983b-68f2-4ace-a614-f04e6783a499.png)

**Comment by Gamebuster19901** [comment]
We must stick to ModLauncher 8.0.9.
