### ISSUE TITLE
No component present: GameSettings

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/WilderForge#30]
```
---- WilderForge Crash Report----
//It appears I have a minor case of very serious brain damage.

Time: 2021-11-25T18:43:28.339022Z
Description: no component present: GameSettings
Stage: POST_INIT

java.lang.RuntimeException: no component present: GameSettings
	at com.worldwalkergames.engine.EntitiesCollection.only(EntitiesCollection.java:234)
	at com.worldwalkergames.legacy.game.campaign.model.GameSettings.in(GameSettings.java:168)
	at com.worldwalkergames.legacy.game.mission.ui.MissionHud.updateTurnPanel(MissionHud.java:1162)
	at com.worldwalkergames.legacy.game.mission.ui.MissionHud.update(MissionHud.java:671)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.engine.Domain.update(Domain.java:81)
	at com.worldwalkergames.legacy.game.mission.ClientMissionDomain.update(ClientMissionDomain.java:126)
	at com.worldwalkergames.legacy.game.mission.ui.MissionScreen$1.update(MissionScreen.java:124)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.game.mission.ui.MissionScreen.update(MissionScreen.java:161)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:545)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:197)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:311)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:117)
	at com.wildermods.wilderforge.launch.Main.launchGame(Main.java:70)
	at com.wildermods.wilderforge.launch.Main.main(Main.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.wildermods.wilderforge.launch.services.WilderLauncherService.lambda$0(WilderLauncherService.java:68)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
---- Additonal Information----

--System Details--
Wildermyth Version: 1.3+363 Dolse Ponder
Operating System: Linux
	Architecture: amd64
	Version: 5.13.0-21-generic
Cores: 24
Memory:
	Max heap size: 7.8 GiB
	Current heap size: 608.0 MiB
	Heap used: 374.5 MiB
	Free heap: 233.5 MiB
Java Version: OpenJDK Runtime Environment 11.0.12+7-Ubuntu-0ubuntu3 
	Vendor: Ubuntu
Uptime: PT17.951S


-- Coremod Details --
Coremods Detected: 5:

	LOADED modlauncher 8.0.9+86+master.3cf110c
	LOADED mixin 0.8.4
	LOADED wildermyth 1.3+363
	LOADED wilderforge 0.0.0.0
	LOADED asm 9.2


```

**Comment by Gamebuster19901** [comment]
This issue first appears in commit f06bf211f45ba05b1a40c39e2a4b8f1eecd93594
